---
title: "techreport2"
format: 
  html:
      embed-resources: true
editor: source
---

## Data

```{r message = FALSE}
set.seed(454)
# load libraries
library(tidyverse) #ofc
library(rstan)
library(readr)
library(bayesplot)
curling <- read_csv("curling.csv") ## make sure to set working directory to source file location
```

```{r}
curling %>%
  mutate(result = ifelse(USWin, "win", "loss")) %>%
  group_by(PowerPlay, result) %>%
  summarize(n=n()) %>%
  ggplot(aes(x=PowerPlay, y=n, fill=result))+
  geom_col()+
  theme_classic()+
  labs(x="Used power play?", y="number of ends", fill="Result")


curling %>%
 mutate(result = ifelse(USWin, "win", "loss")) %>%
  group_by(Points, result) %>%
  summarize(n = n()) %>%
  ggplot(aes(x=Points, y=n, fill=result))+
  geom_col(position="dodge")+
  theme_classic()+
  labs(fill="Result", y="number of ends")
```



## Models


```{r output=FALSE}
set.seed(454)
## Complete Pooling approach

# Make data object
run_data <- list(N = nrow(curling),
                 x = curling$PowerPlay,
                 y = curling$USWin,
                 z = curling$Points, 
                 m0 = 0,
                 m1 = 0,
                 m2 = 0,
                 s0 = 2,
                 s1 = 2,
                 s2 = 2)

# Fit model in Stan
fit <- stan(file = "completepooling.stan", ## make sure to set working directory to source file location
            data = run_data, 
            chains = 4, 
            warmup = 1000,
            iter = 2000)
```

```{r output=FALSE}
set.seed(454)
## Partial Pooling approach (STILL BUGGY)

# making unique indices for each match 
curling <- curling %>%
  mutate(k=as.integer(as.factor(CompetitionName)), # competition indices
         uniqueMatchID = str_c(MatchID, k),
         j = as.integer(as.factor(uniqueMatchID)) # match indices (all matches across competitions have a unique)
         )
  

# Make data object
run_data_partial <- list(N = nrow(curling),
                 x = as.integer(curling$PowerPlay),
                 y = curling$USWin,
                 z = curling$Points,
                 n_competitions = length(unique(curling$CompetitionName)),
                 j = as.integer(as.factor(curling$CompetitionName)), # competition indices
                 u0=0, u1=0, u2=0, 
                 v0=1, v1=1, v2=2, 
                 # how to choose good priors for these?
                 alpha0=1, alpha1=1, alpha2=1,
                 eta0=1, eta1=1, eta2=1
               )

# Fit model in Stan
fit_partial <- stan(file = "partialpooling2.stan", ## make sure to set working directory to source file location
            data = run_data_partial, 
            chains = 4, 
            warmup = 1000,
            iter = 2000)
```
## Results

### Convergence Diagnostics 

#### Complete pooling

```{r}
# Rhat
Rhat(extract(fit, pars = "beta0", permuted = FALSE)[,,1]) 
Rhat(extract(fit, pars = "beta1", permuted = FALSE)[,,1])

# bulk-ESS
ess_bulk(extract(fit, pars = "beta0", permuted = FALSE)[,,1])
ess_bulk(extract(fit, pars = "beta1", permuted = FALSE)[,,1])
```

```{r}
traceplot(fit, pars = "beta0", inc_warmup = TRUE)
traceplot(fit, pars = "beta1", inc_warmup = TRUE)
traceplot(fit, pars = "beta2", inc_warmup = TRUE)
```

```{r}
# autocorrelation plot
stan_ac(fit, pars = c("beta0","beta1", "beta2"), size=0.5)
```

#### Partial Pooling

```{r}
beta0rhats <- rep(NA, 4)
beta1rhats <- rep(NA,4)
beta2rhats <- rep(NA, 4)
beta0ESS <- rep(NA, 4)
beta1ESS <- rep(NA, 4)
beta2ESS <- rep(NA, 4)

# for each of the 4 competitions, calculate the Rhat and bulk ESS of beta0, beta1, and beta2
for(i in 1:13){
  beta0rhats[i] <- Rhat(extract(fit_partial, pars = "beta0", permuted = FALSE)[,,i])
  beta1rhats[i] <- Rhat(extract(fit_partial, pars = "beta1", permuted = FALSE)[,,i])
  beta2rhats[i] <- Rhat(extract(fit_partial, pars = "beta2", permuted = FALSE)[,,i])
  
  beta0ESS[i] <- ess_bulk(extract(fit_partial, pars = "beta0", permuted = FALSE)[,,i])
  beta1ESS[i] <- ess_bulk(extract(fit_partial, pars = "beta1", permuted = FALSE)[,,i])
  beta2ESS[i] <- ess_bulk(extract(fit_partial, pars = "beta2", permuted = FALSE)[,,i])
}

# put all this into a table to display
summary_measures <- data.frame(competition=1:4, beta0_rhat =beta0rhats, beta0_ESS = beta0ESS, beta1_rhat = beta1rhats, beta1_ESS = beta1ESS, beta2_rhat = beta2rhats, beta2_ESS = beta2ESS)
knitr::kable(summary_measures)
```


### Regression Coefficients 

#### Complete Pooling

```{r}
posterior_data_complete <- as.data.frame(fit)

# estimates and credible intervals of exponentiated coefficients 
# (so represent multiplicative change in odds of winning)
mean(exp(posterior_data_complete$beta0))
quantile(exp(posterior_data_complete$beta0), c(0.05, 0.95))
mean(exp(posterior_data_complete$beta1)) # coefficient for X, power play 
quantile(exp(posterior_data_complete$beta1), c(0.05, 0.95))
mean(exp(posterior_data_complete$beta2)) # coefficient for Z, effectiveness
quantile(exp(posterior_data_complete$beta2), c(0.05, 0.95))
```

#### Partial Pooling
